--[[
    init.lua
    Created: 04/23/2025 17:22:41
    Description: Autogenerated script file for the map test_hub.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local test_hub = {}

-------------------------------
-- Map Callbacks
-------------------------------
---test_hub.Init(map)
--Engine callback function
function test_hub.Init(map)


end

---test_hub.Enter(map)
--Engine callback function
function test_hub.Enter(map)

  GAME:FadeIn(20)

end

---test_hub.Exit(map)
--Engine callback function
function test_hub.Exit(map)


end

---test_hub.Update(map)
--Engine callback function
function test_hub.Update(map)


end

---test_hub.GameSave(map)
--Engine callback function
function test_hub.GameSave(map)


end

---test_hub.GameLoad(map)
--Engine callback function
function test_hub.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function test_hub.North_Exit_Touch(obj, activator)
	
	local dungeon_entrances = {'test_forest'}
	local ground_entrances = {}
	COMMON.ShowDestinationMenu(dungeon_entrances, ground_entrances)
end
function test_hub.East_Exit_Touch(obj, activator)
	GAME:FadeOut(false, 20)
	GAME:EnterGroundMap("test_town", "West_Entrance")
end

function test_hub.Test_Assembly_Mailbox_Action(obj, activator)
	
end
function test_hub.Test_Pikachu_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Pikachu')
	UI:SetSpeaker(npc)
	UI:WaitShowDialogue("Hello, hero!")
	UI:WaitShowDialogue("That sign is the Assembly. It'll be a Mailbox later!")
end
function test_hub.Test_Chikorita_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Chikorita')
	UI:SetSpeaker(npc)
	UI:WaitShowDialogue("Hey, are you new? Have you seen Test Forest? You should totally check it out!")
	COMMON.UnlockWithFanfare('test_forest', false)
end
function test_hub.Test_Celebi_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Celebi')
	UI:SetSpeaker(npc)
	UI:WaitShowDialogue("I'm a cutscene expert. Come back later and I'll show you!")
end
return test_hub

