--[[
    init.lua
    Created: 04/25/2025 09:46:01
    Description: Autogenerated script file for the map test_town.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local test_town = {}

-------------------------------
-- Map Callbacks
-------------------------------
---test_town.Init(map)
--Engine callback function
function test_town.Init(map)


end

---test_town.Enter(map)
--Engine callback function
function test_town.Enter(map)

  GAME:FadeIn(20)

end

---test_town.Exit(map)
--Engine callback function
function test_town.Exit(map)


end

---test_town.Update(map)
--Engine callback function
function test_town.Update(map)


end

---test_town.GameSave(map)
--Engine callback function
function test_town.GameSave(map)


end

---test_town.GameLoad(map)
--Engine callback function
function test_town.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------
function test_town.West_Exit_Touch(obj, activator)
	GAME:FadeOut(false, 20)
	GAME:EnterGroundMap("test_hub", "East_Entrance")
end
function test_town.North_Text_Box_Touch(obj, activator)
	UI:ResetSpeaker()
	UI:SetAutoFinish(true)
	UI:WaitShowDialogue("You can't go here right now.")
end
function test_town.Test_Espeon_Access_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Espeon')
	UI:SetSpeaker(npc)
	UI:WaitShowDialogue("I'll look different in the final game! Come back later for our shop!")
end
function test_town.Test_Umbreon_Access_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Umbreon')
	UI:SetSpeaker(npc)
	UI:WaitShowDialogue("I'll look different in the final game! Come back later for our shop!")
end
function test_town.Test_Leafeon_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Leafeon') --obtain the NPC
	UI:SetSpeaker(npc) --set it to the dialogue box
	UI:WaitShowDialogue("I'll look different in the final game! Come back later for the Pokepedia!")
end
function test_town.Test_Slorpp_Access_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Slorpp')
	UI:SetSpeaker(npc)
	UI:WaitShowDialogue("I'll be a Slorpp in the final game! Come back later to see my move shop!")
end
function test_town.Test_Kotora_1_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Kotora_1')
	UI:SetSpeaker(npc)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue("Angry")
	UI:SetSpeakerEmotion("Crying")
	UI:WaitShowDialogue("Crying")
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue("Determined")
	UI:SetSpeakerEmotion("Dizzy")
	UI:WaitShowDialogue("Dizzy")
end
function test_town.Test_Kotora_2_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Kotora_2')
	UI:SetSpeaker(npc)
	UI:SetSpeakerEmotion("Happy")
	UI:WaitShowDialogue("Happy")
	UI:SetSpeakerEmotion("Inspired")
	UI:WaitShowDialogue("Inspired")
	UI:SetSpeakerEmotion("Joyous")
	UI:WaitShowDialogue("Joyous")
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue("Normal")
end
function test_town.Test_Kotora_3_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Kotora_3')
	UI:SetSpeaker(npc)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue("Pain")
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue("Sad")
	UI:SetSpeakerEmotion("Shouting")
	UI:WaitShowDialogue("Shouting")
	UI:SetSpeakerEmotion("Sigh")
	UI:WaitShowDialogue("Sigh")
end
function test_town.Test_Kotora_4_Action(obj, activator)
	UI:ResetSpeaker()
	local npc = CH('Test_Kotora_4')
	UI:SetSpeaker(npc)
	UI:SetSpeakerEmotion("Stunned")
	UI:WaitShowDialogue("Stunned")
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue("Surprised")
	UI:SetSpeakerEmotion("Teary-eyed")
	UI:WaitShowDialogue("Teary-eyed")
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue("Worried")
end
return test_town

