--[[
    init.lua
    Created: 04/23/2025 17:42:43
    Description: Autogenerated script file for the map test_hub.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local test_hub = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---test_hub.Init(zone)
--Engine callback function
function test_hub.Init(zone)


end

---test_hub.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function test_hub.EnterSegment(zone, rescuing, segmentID, mapID)


end

---test_hub.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function test_hub.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---test_hub.Rescued(zone, name, mail)
--Engine callback function
function test_hub.Rescued(zone, name, mail)


end

return test_hub

