--[[
    init.lua
    Created: 04/27/2025 22:41:54
    Description: Autogenerated script file for the map test_pond.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local test_pond = {}

-------------------------------
-- Map Callbacks
-------------------------------
---test_pond.Init(map)
--Engine callback function
function test_pond.Init(map)


end

---test_pond.Enter(map)
--Engine callback function
function test_pond.Enter(map)

	if SV.test_pond.BossComplete then
		test_pond.PostBattle()
	else
		test_pond.PreBattle()
	end
end
function test_pond.PreBattle()
	local player = CH("PLAYER")
	local enemy = CH("Croco")
	
	GAME:CutsceneMode(true)
	
	UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 20)
	GAME:WaitFrames(30)
	UI:WaitHideTitle(20)
	
	GAME:MoveCamera(180, 172, 1, false)
	
	GAME:FadeIn(20)
	
	GROUND:MoveToPosition(player, 172, 192, false, 2)
	
	GROUND:CharSetEmote(player, "exclaim", 1)
	
	SOUND:PlayBGM("", false)
	
	UI:SetSpeaker(STRINGS:Format("\\uE040"))
	UI:WaitShowDialogue("Stop right there!")
	
	SOUND:PlayBattleSE("DUN_Aqua_Tail")
	local emitter = RogueEssence.Content.SingleEmitter(RogueEssence.Content.AnimData("Aqua_Tail_Splash", 3))
	emitter.LocHeight = 8
	GROUND:PlayVFX(emitter, enemy.Bounds.Center.X, enemy.Bounds.Center.Y)
	GROUND:Unhide("Croco")
	
	GAME:WaitFrames(60)
	
	SOUND:PlayBGM("Threat.ogg", false)
	
	UI:SetSpeaker(enemy)
	UI:WaitShowDialogue("I dunno who you are,[pause=30] but yer on my property!")
	UI:WaitShowDialogue("Didn't ya read the sign?")
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue("Trespassers[pause=0] get chomped!")
	SOUND:PlayBattleSE("EVT_Roar")
	GROUND:CharSetAnim(enemy, "Shoot", false) --animates once
	
	GAME:WaitFrames(30)
	COMMON.BossTransition(preserveMusic)
	GAME:CutsceneMode(false)
	GAME:ContinueDungeon('test_forest', 1, 0, 0)
end

function test_pond.PostBattle()

	local player = CH("PLAYER")
	local enemy = CH("Croco")
	
	GAME:CutsceneMode(true)
	
	GAME:MoveCamera(180, 172, 1, false)
	GROUND:TeleportTo(player, 172, 192, Direction.Up) 
	
	GROUND:Unhide("Croco")

	GAME:FadeIn(20)
	UI:SetSpeaker(enemy)
	UI:WaitShowDialogue("Alright, fine![pause=0] I'll hear what you have to say!")
	
	local mon_id = RogueEssence.Dungeon.MonsterID("croconaw", 0, "normal", Gender.Male)
	local recruit = _DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, mon_id, 3, "", 0)
	COMMON.JoinTeamWithFanfare(recruit, false)
	
	GAME:FadeOut(false, 20)
	
	GAME:CutsceneMode(false)
	
	COMMON.EndDungeonDay(RogueEssence.Data.GameProgress.ResultType.Cleared, "test_hub", -1, 0, 0)
end

---test_pond.Exit(map)
--Engine callback function
function test_pond.Exit(map)


end

---test_pond.Update(map)
--Engine callback function
function test_pond.Update(map)


end

---test_pond.GameSave(map)
--Engine callback function
function test_pond.GameSave(map)


end

---test_pond.GameLoad(map)
--Engine callback function
function test_pond.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return test_pond

