--[[
    init.lua
    Created: 04/26/2025 11:40:25
    Description: Autogenerated script file for the map test_forest.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local test_forest = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---test_forest.Init(zone)
--Engine callback function
function test_forest.Init(zone)


end

---test_forest.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function test_forest.EnterSegment(zone, rescuing, segmentID, mapID)


end

---test_forest.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function test_forest.ExitSegment(zone, result, rescue, segmentID, mapID)
	if result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
		local base_camp = {test_hub}
		COMMON.EndDungeonDay(result, "test_hub", -1, 0, 0)
	else
		if segmentID == 0 then
			GAME:EnterZone('test_forest', -1, 0, 0)
		else	
			--COMMON.EndDungeonDay(result, "test_hub", -1, 0, 0)
			SV.test_pond.BossComplete = true
			GAME:EnterZone('test_forest', -1, 0, 0)
		end
	end	
end

---test_forest.Rescued(zone, name, mail)
--Engine callback function
function test_forest.Rescued(zone, name, mail)


end

return test_forest

